#!/bin/sh
echo '********** BEGINING PIPELINE **********'
echo '********** SSH INTO KUBEVIRT VM **********'
ssh ubuntu@192.168.4.93 <<EOF
 echo '********** SSH SUCESSFUL **********'
 cd ~/nodejs-app
 # whoami
 echo '********** PULLING LATEST GITHUB COMMIT **********'
 git pull
 # pwd
 echo '********** UPDATING NODE DEPENDENCIES **********'
 npm install
 echo '********** RESTARTING WEBSERVER **********'
 pm2 restart all
 exit
EOF
echo '********** PIPELINE COMPLETE **********'
